development:
  adapter: postgresql
  encoding: unicode
  database: bechdel_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: bechdel_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bechdel_production
  pool: 5
  username:
  password:
